### PR TITLE
adding class test....

### PR DESCRIPTION
**Pull request by EnnasryAbdelaziz**
I m adding a new class Test to repository bankservices

### CODE REVIEW

**Comment by ennasry-abdelaziz** [comment]
your code seems good but you have to add conditions test

**Comment by EnnasryAbdelaziz** [comment]
I have added th additional ondition please check and approave

**Comment by ennasry-abdelaziz** [comment]
Hi Abdel your code looks good go ahead and merge

**Comment by EnnasryAbdelaziz** [comment]
merge ok

**Pull request merged**
